### ISSUE TITLE
lsmeans is being deprecated

### ISSUE THREAD

**Issue by rvlenth** [JWiley/JWileymisc#2]
I note that **JWileymisc** imports the **lsmeans** package. However, **lsmeans** is about to be deprecated. The newer package **emmeans** replaces it and works in much the same way. There are vignettes and utilities to convert **lsmeans** scripts and workspaces. 

I suggest that you update to **emmeans** as soon as possible, This is made perhaps more urgent by the fact that I received a message that **lsmeans** is failing some tests due to increased stringency in the tests regarding the use of Suggests packages. Until I saw that a new package imports **lsmeans**, I was prepared to answer that this would be a good time to formally deprecate **lsmeans**, rather than fix the package to pass the tests.

**Comment by JWiley** [comment]
@rvlenth Thanks for the heads up.  I took a quick look at *emmeans* and should not have an issue moving over.  Does it help in just deprecating that package if you can tell CRAN maintainers that I will transition JWileymisc off it in the next 1-2 weeks?

**Comment by JWiley** [comment]
emmeans used now
