### ISSUE TITLE
issue with testthat test-distributions.R - line 67

### ISSUE THREAD

**Issue by yrosseel** [JWiley/JWileymisc#4]
Hi,
This came up during revdep checks for lavaan. In the test-distributions.R file (in tests/testthat), you now have (lines 65-67)

```r
x <- as.data.frame(scale(mtcars[, 1:3]))
x[1, 1] <- NA
expect_warning(m <- testDistribution(x, distr = "mvnormal", use = "fiml"))
```

However, the last expression runs without producing a warning, and therefore, this 'test' fails, as it was expecting a warning. Could you please adapt this line, and update JWileymisc on CRAN? (It would otherwise prevent lavaan from being updated).
Thanks,
Yves.

**Comment by JWiley** [comment]
fixed and submitted to CRAN
