### ISSUE TITLE
could not find function "testdistr"

### ISSUE THREAD

**Issue by Xiumingmingming** [JWiley/JWileymisc#5]
Hi,

I'm trying to reproduce your code from your book:

> set.seed(1234)
d2 <- data.table(x = rnorm(500)) 
d2[, y := ifelse(abs(x) > 1, x, -x)]
plot_grid(
testdistr(d2$x, plot = FALSE)$Density, 
testdistr(d2$y, plot = FALSE, varlab = "Y")$Density, 
ncol = 2)

By which I got an error:

> could not find function "testdistr"

I have installed and attached the "JWileymisc" package and all the other packages. 
I'm wondering whether that's because I couldn't install those updates:

> Rcpp     1.0.4.6   1.0.5              
> processx   3.4.2   3.4.3           
> mnormt     2.0.0   2.0.1            
> nloptr   1.2.2.1 1.2.2.2       

       
My R version is 4.0.2. Do you have any suggestions for that?

**Comment by JWiley** [comment]
@Xiumingmingming this has been renamed for clarity in more recent versions and is now: `testDistribution()`.
Its also added more methods in place so it is more flexible and can integrate better with model diagnostics testing, see:
http://joshuawiley.com/JWileymisc/articles/diagnostics-vignette.html
If you want to reproduce that book code exactly, would need to use an older version, but I'd suggest just updating to `testDistribution()`. You might also run into some other changes along the way, which are mostly addressed here:
http://joshuawiley.com/JWileymisc/articles/model-test-vignette.html
and 
http://joshuawiley.com/multilevelTools/articles/lmer-vignette.html
